### ISSUE TITLE
2022.2.x Release and Release notes missing on Github

### ISSUE THREAD

**Issue by StefanBruens** [oneapi-src/oneVPL#74]
Although 2022.2.x has seen several patch versions, it is not available as a ["release"](https://github.com/oneapi-src/oneVPL/releases).

Release notes are completely missing, some information for 2022.2.0 is available here:
https://www.intel.com/content/www/us/en/developer/tools/oneapi/onevpl.html#gs.ce7b1t
>  - Multiple hardware adapters are supported as part of the 2.6 API update. They provide faster performance by taking advantage of available platform resources.
>   - Windows* 11, Microsoft Visual Studio* 2022, and Microsoft Windows Server* 2022 have been added to include support for the latest development environments.
>   - MPEG2 decode is now supported in a CPU implementation to improve codec coverage for systems that do not have dedicated hardware.
>   - For a complete list of new features, see the [Release Notes](https://www.intel.com/content/www/us/en/developer/articles/release-notes/oneapi-video-processing-library-release-notes.html).

In the past (e.g. https://github.com/oneapi-src/oneVPL/releases/tag/v2021.2.2) even patch releases had release notes.

**Comment by mav-intel** [comment]
Release created.

**Comment by StefanBruens** [comment]
Current version should be 2022.2.4, not 2022.2.0.

Phoronix already got fooled ...

**Comment by mav-intel** [comment]
@StefanBruens Currently GitHub releases are set up to correspond with the version of oneVPL shipped as part of oneAPI so folks can easily find the corresponding code to shipped binaries.

We have been discussing having some sort of changelog file in the repo to allow easier tracking of changes for non oneAPI releases. Would this meet your needs?

**Comment by kepstin** [comment]
Right now according to github, if you go to the "Releases" tab, `v2022.2.0` is the "latest release"… but there have been several tagged updates since then.

It would be helpful to create github releases for all of the tagged point releases as well, mostly to ensure that anyone coming to github to fetch oneVPL would get the latest point release like `2022.2.5` (which presumably has some bug fixes?) rather than the initial `2022.2.0` release.

I would expect the notes on the point release to only describe incremental changes - you could provide a link back to the initial major version update if desired.

**Comment by mav-intel** [comment]
Going forward we will create a GitHub release for each tagged point release
