### ISSUE TITLE
How to select different devices with MFXLoad and MFXCreateSession API

### ISSUE THREAD

**Issue by gitcchi** [oneapi-src/oneVPL#86]
I have both an Intel Arc as well as an Intel UHD 770 iGPU, and would like to be able to select which hardware to use.
I could not find what is the way to select the hardware adapter with the newer Load and CreateSession method. The documentation only mention it with the legacy API. 

Could a code sample be provided that demonstrates this functionality?

**Comment by rupakroyintel** [comment]
@gitcchi Thanks for reaching out to us. For the 2.x APIs it is recommended to use [MFXEnumImplementations](https://fuzzy-journey-a9987507.pages.github.io/API_ref/VPL_disp_api_func.html#mfxenumimplementations)() and [MFXSetConfigFilterProperty()](https://fuzzy-journey-a9987507.pages.github.io/API_ref/VPL_disp_api_func.html#mfxsetconfigfilterproperty) to query adapter capabilities and select a suitable adapter from the available hardware adapters as MFXQueryAdapters()* are deprecated starting from API 2.9. You can see the [hello-createsession](https://github.com/oneapi-src/oneVPL/tree/master/examples/hello/hello-createsession) code example that shows the usage of these APIS. One of the major advantages of using 2. x APIs is that VPL runtime can allocate the video memory surfaces itself instead of the application doing so ("Internal Memory Management") and can also create the DX/VAAPI device internally instead of the app doing so and then calling SetHandle. More information can be found on this [page](https://fuzzy-journey-a9987507.pages.github.io/programming_guide/VPL_prg_hw.html#new-model-to-work-with-hardware-acceleration).

**Comment by gitcchi** [comment]
@rupakroyintel Thank you for your reply, but it unfortunately does not help me fill in the holes. The hello-createsession code does not use MFXEnumImplementations and MFXSetConfigFilterProperty.

I can use the MFXEnumImplementations and with it I can see the two Intel devices. The missing part is how to set the config. 
The [mfxImplDescription](https://spec.oneapi.io/versions/latest/elements/oneVPL/source/API_ref/VPL_disp_api_struct.html#id4) does not have a field for implementation **index**, only one for implementation **type**. This field is set with MFX_IMPL_TYPE_HARDWARE. 

Can you post an example of the MFXSetConfigFilterProperty calls with arguments that will select the implementation? Currently it is not clear which fields need to be set to select the device.

Also the documentation text of [MFXEnumImplementations]{https://spec.oneapi.io/versions/latest/elements/oneVPL/source/API_ref/VPL_disp_api_func.html?highlight=enumim#id4} I believe needs updating as it still assumes the output handle is a [mfxImplDescription](https://spec.oneapi.io/versions/latest/elements/oneVPL/source/API_ref/VPL_disp_api_struct.html#structmfx_impl_description).
This is now an opaque [mfxHDL](https://spec.oneapi.io/versions/latest/elements/oneVPL/source/API_ref/VPL_ref_types.html#_CPPv46mfxHDL) as you can select the type of info to query with the **format** argument.

**Comment by gitcchi** [comment]
@rupakroyintel Also 3 of the 4 links in your reply I cannot access. I get "Unauthorized access error".

**Comment by jonrecker** [comment]
More information and example code for selecting from among multiple GPUs is included in the guide [here](https://github.com/oneapi-src/oneVPL/blob/master/doc/multi-adapter-guide.md). The application may either user MFXSetConfigFilterProperty() to filter out implementations which do not match the desired adapter, and/or iterate over all available implementations using MFXEnumImplementations() then call MFXCreateSession() with the index "i" corresponding to the desired GPU. Some other examples of using MFXSetConfigFilterProperty with mfxExtendedDeviceId are in the unit tests [here](https://github.com/oneapi-src/oneVPL/blob/master/dispatcher/test/unit/src/dispatcher_common.cpp#L83).

MFXEnumImplementations always returns an opaque handle of type mfxHDL, which should be interpreted (cast) based on which "format" was requested. The [vpl-inspect tool](https://github.com/intel-innersource/frameworks.media.onevpl.dispatcher/blob/main/tools/cli/vpl-inspect.cpp) has examples of using MFXEnumImplementations().

**Comment by rupakroyintel** [comment]
> @rupakroyintel Also 3 of the 4 links in your reply I cannot access. I get "Unauthorized access error".

Sorry for the inconvenience. I have updated the links.

**Comment by gitcchi** [comment]
@jonrecker Thank you for the explanation and the link. With it I was able to successfully select the adapter using the filtering out method, by configuring the VendorID and VendorImplID with MFXSetConfigFilterProperty. I will try the MFXCreateSession index "i" appoach as well once my card is back from RMA, but I expect that approach to work as well.

My mention of the issue with [MFXEnumImplementations](https://spec.oneapi.io/versions/latest/elements/oneVPL/source/API_ref/VPL_disp_api_func.html?highlight=enumim#id4) is specifically with the spec text in the link. It assumes it can only be an [mfxImplDescription](https://spec.oneapi.io/versions/latest/elements/oneVPL/source/API_ref/VPL_disp_api_struct.html#structmfx_impl_description), while as you mention it is an opaque mfxHDL. I assumed it was wrong because it was outdated, but if you say it has always been an opaque mfxHDL, then it is just wrongly described.

**Comment by gitcchi** [comment]
@rupakroyintel Thanks, I can confirm the links work for me now.
